changelog:
  categories:
    - title: New Features 🎉
      labels:
        - new
    - title: Improvements 🛠️
      labels:
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - fix
    - title: Changes 🔄
      labels:
        - change
