changelog:
  categories:
    - title: New Features 🎉
      labels:
        - feat
    - title: Improvements 🛠️
      labels:
        - change
    - title: Deprecated ⚠️
      labels:
        - deprecate
    - title: Removed ⛔️
      labels:
        - remove
    - title: Bug Fixes 🐞
      labels:
        - fix
    - title: Security 🚨
      labels:
        - security
