changelog:
  categories:
    - title: New Features 🎉
      labels:
        - highlight
    - title: Improvements 🛠️
      labels:
        - enhancement
      exclude:
        - labels:
            - highlight
    - title: Bug Fixes 🐞
      labels:
        - bugfix
        - hotfix

